# -*- coding: utf-8 -*-
"""Python Datatypes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dQ5oovqphLyBE29ZvHriYW9XsIRprYC3
"""

## Adding prices of list of items

prices: list=[10,20,40,5,100]
prices.append(200)
prices.remove(5)

sum: int = 0
for price in prices:
  sum+=price
print(f"Total Cost:   {sum}")
print(f"Actual Prices List:    {prices}")

#Finding Student Average marks

student_marks: dict =  {"Ali": 60, "Saad": 50, "Qamar": 90, "Samra": 40}
sum: int = 0
for k, v in student_marks.items():
  print(f"{k}: {v}")
  # sum += value

# for key in student_marks:
#   print(key)

# print("Total Marks:   ", sum)

#** Getting nique items from list **

visits: list = [1,2,47.8,4,1,2,5,4,5,4]
unique_visits: set = set(visits)
for values in unique_visits:
  print(values)

# Temperature Conversions from a list of temperatures

temp_list: list = [20, 30, 40, 50, 37]
f_result: float
for t in temp_list:
    f_result = (t * 9 / 5) + 32
    print(f_result)

##F indint salary of employee by searching it's id

emp_record: list = [
    (11, "Shaid", 50000),
    (43, "Ali", 40000),
    (99, "Saad", 56000),
    (23, "Mohsin", 232333),
]
searching_id = input("Please enter employee ID to check salary:     ")
searching_id = int(searching_id)
# searched_record: tuple = ()
for tup in emp_record:
    # searched_record = any(searching_id in tup for tup in emp_record)
    if searching_id in tup:
        print(tup)
    else:
        print(f"Employee having ID \'{searching_id}\' not found")
        break

sentence: str= """The fox is quick and the dog is lazy.
FOX is amazing! The Dog runs fast, but the Fox runs faster.
Quick as a fox, the dog chases the FOX.
The quick brown fox and the lazy dog are best friends.
Fox and Dog play together every day"""

sentence = sentence.lower()

searching_word = input("Please enter a word to search:     ")
searching_word = searching_word.lower()

accorances: int = sentence.count(searching_word)
if sentence.count(searching_word)>0:
  print(f"{searching_word} found")
  print(accorances)
else:
  print(f"{searching_word} not found")

# Searching item in inverntory

inventroy: dict= {"mouse": 40, "LCD": 20, "Keyboard": 50, "wires": 100}

searching_item = input("Please enter item name to search:     ")
found: bool= False
for key, value in inventroy.items():
  if searching_item.lower() == key.lower():
    print(f"{key}: {value}")
    found = True
    break
if not found:
  print(f"\'{searching_item}\' not found")

# finding commond friends of two people

person1: set={"Ali", "Fraz", "Mohsin", "Ali", "Saad", "Hassan", "Umer"}
person2: set = {"Fizza", "Mohsin", "Tayyab", "ali"}

# person1= {name.casefold() for name in person1}
# person2= {name.casefold() for name in person2}

person1= {name.capitalize() for name in person1}
person2= {name.capitalize() for name in person2}

print(person1)
print(f"Both Persons have common friends:   {person1 & person2}")

