# -*- coding: utf-8 -*-
"""Python Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1juhVads1eyZ6czKf0uAwHUBZUWP3pCgL
"""

#  First Python program

name: str="John"
age: int=35
grade: str="A"
cgpa: float=3.4
def student_data():
  print(f"Student name is {name}, {age} years old having grade '{grade}' and CGPA {cgpa}")
student_data()

# Calculting caffe bill

from datetime import datetime

cust_name: str=input("Your Good Name:   ")
contact: int=input("Contact:   ")
first_item: str=input("Your first food choice:    ")
second_item: str=input("Your second food choice:   ")
third_item: str=input("Your second food choice:   ")

print(f"""------------JEFF CAFE---------
Customer Name:    {name}           Date:    {datetime.now()}
------------------------------------------------
    ITEM                        PRICE
  {first_item}                  500
  {second_item}                 300
  {third_item}                  340
  ----------------------------------------------
  TOTAL                         1140

  ---     Thank for shopping!    ----
""")

